extends:
- google
- eslint:recommended
- plugin:react/recommended

env:
  browser: true
  es6: true
  mocha: true
  node: true

parser: babel-eslint

plugins:
- react
- mocha

settings:
  react:
    version: detect

rules:
  react/prop-types: off
