package de.fu_berlin.inf.dpp.feedback;

import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * This class was auto-generated by Eclipse and is used to access the strings in
 * messages.properties.
 */
public class Messages {
  private static final String BUNDLE_NAME = "de.fu_berlin.inf.dpp.feedback.messages"; // $NON-NLS-1$

  private static final ResourceBundle RESOURCE_BUNDLE = ResourceBundle.getBundle(BUNDLE_NAME);

  private Messages() {
    // do nothing
  }

  /**
   * Returns the value for the given key.
   *
   * @param key
   * @return the value for the key as a String
   */
  public static String getString(String key) {
    try {
      return RESOURCE_BUNDLE.getString(key);
    } catch (MissingResourceException e) {
      return '!' + key + '!';
    }
  }
}
