# Has to be the same name as in build_doc in order to require the same check in GitHub
name: Build

on:
  push:
    paths-ignore:
    - 'docs/**'
  pull_request:
    paths-ignore:
    - 'docs/**'

jobs:

  formatter:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: m273d15/java-format-action@v1.1
      with:
        version: '1.6'

  build:
    runs-on: ubuntu-latest

    steps:
    # Pre-Build
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Determine short sha
      id: short-sha
      run: |
        short_sha=$(git rev-parse --short=10 $GITHUB_SHA)
        echo "::set-output name=short_sha::$short_sha"
        echo "::set-env name=SHORT_SHA::$short_sha"
      shell: 'bash'

    # Uncomment <depends> entries in order to make Saros/I installable in all JetBrains IDEs
    - name: Prepare Saros/I plugin.xml
      if: github.ref == 'refs/heads/master'
      run: |
        sed -i 's/<!--depends/<depends/g' intellij/resources/META-INF/plugin.xml
        sed -i 's/depends-->/depends>/g' intellij/resources/META-INF/plugin.xml

    # Build
    - name: Build and test with Gradle
      run: |
        ./gradlew \
          -PskipTestSuites=true \
          -PuseBuildScan=true \
          -PaggregateTestResults=true \
          -PversionQualifier=DEV-$SHORT_SHA \
          -DmaxParallelForks=4 \
          --no-daemon \
          --parallel \
          sarosEclipse sarosIntellij sarosServer sarosLsp

    # Post-Build
    # Success-Case
    - name: Upload eclipse build
      uses: actions/upload-artifact@v1
      if: success() && github.ref == 'refs/heads/master'
      with:
        name: saros-eclipse-dev-${{ steps.short-sha.outputs.short_sha }}
        path: build/distribution/eclipse

    - name: Upload intellij build
      uses: actions/upload-artifact@v1
      if: success() && github.ref == 'refs/heads/master'
      with:
        name: saros-intellij-dev-${{ steps.short-sha.outputs.short_sha }}
        path: build/distribution/intellij

    - name: Upload server build
      uses: actions/upload-artifact@v1
      if: success() && github.ref == 'refs/heads/master'
      with:
        name: saros-server-dev-${{ steps.short-sha.outputs.short_sha }}
        path: build/distribution/server

    - name: Upload lsp build
      uses: actions/upload-artifact@v1
      if: success() && github.ref == 'refs/heads/master'
      with:
        name: saros-lsp-dev-${{ steps.short-sha.outputs.short_sha }}
        path: build/distribution/lsp

    # Failure-Case
    - name: Check test report
      id: check-report
      if: failure()
      run: |
        [ -d 'build/reports/allTests' ] && echo "::set-output name=report-exist::true" || echo "::set-output name=report-exist::false"
      shell: 'bash'

    - name: Upload test results
      uses: actions/upload-artifact@v1
      if: failure() && steps.check-report.outputs.report-exist == 'true'
      with:
        name: test-results-${{ github.sha }}
        path: build/reports/allTests
